# Generated by Django 4.0.4 on 2022-05-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chapitre', models.CharField(max_length=50, unique=True)),
                ('nbre_partie', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_partie', models.CharField(max_length=50)),
                ('chapitre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generate.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=300, unique=True)),
                ('nbre_point', models.IntegerField(default=1)),
                ('picture', models.ImageField(upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_question', models.CharField(default='QRO', max_length=20)),
                ('niveau', models.CharField(default='moyen', max_length=15)),
                ('partie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='generate.partie')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_rep', models.CharField(max_length=256)),
                ('bonne_rep', models.CharField(max_length=256)),
                ('mauvaise_rep', models.CharField(max_length=256)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.question')),
            ],
        ),
    ]
