# Generated by Django 4.0.5 on 2022-06-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chapitre', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.course')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('chapitre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generate.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_question', models.CharField(choices=[('QRO', 'QRO'), ('QRC', 'QRC'), ('Question_trou', 'Question_trou'), ('VRAI/FAUX', 'VRAI/FAUX')], max_length=20, null=True)),
                ('niveau', models.CharField(choices=[('facile', 'facile'), ('moyen', 'moyen'), ('difficile', 'difficile')], max_length=200)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.partie')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=256)),
                ('state', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.question')),
            ],
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_epreuve', models.CharField(max_length=25)),
                ('chemin', models.URLField()),
                ('type_epreuve', models.CharField(choices=[('Controle continu', 'CC'), ('Session Normal', 'SN')], max_length=25)),
                ('annee', models.DateField(auto_now_add=True)),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generate.correction')),
            ],
        ),
    ]
