# Generated by Django 4.0.3 on 2022-06-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epreuve',
            name='chemin',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='contenue',
            field=models.TextField(default=1),
        ),
    ]
