# Generated by Django 4.0.3 on 2022-06-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_remove_epreuve_chemin_epreuve_contenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epreuve',
            name='correction',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='correction',
            field=models.ManyToManyField(related_name='epreuve', to='generate.correction'),
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_exercice', models.CharField(max_length=25)),
                ('contenue', models.TextField(default=1)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generate.correction')),
            ],
        ),
    ]
